name: recipe_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  get: 4.6.6
  hive_ce: 2.5.0+2
  hive_ce_flutter: 2.0.0
  flutter_form_builder: 9.4.1
  form_builder_validators: 11.0.0
  uuid: 4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
